// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/logos-moysesnet/LogoModelo1.tsx": () => import("../components/mockups/logos-moysesnet/LogoModelo1.tsx"),
  "./components/mockups/logos-moysesnet/LogoModelo2.tsx": () => import("../components/mockups/logos-moysesnet/LogoModelo2.tsx"),
  "./components/mockups/logos-moysesnet/LogoModelo3.tsx": () => import("../components/mockups/logos-moysesnet/LogoModelo3.tsx"),
  "./components/mockups/landing-enam/LandingEnam.tsx": () => import("../components/mockups/landing-enam/LandingEnam.tsx")
};
